#!/usr/bin/bash

programname=$(basename $0)

function usage() {
cat << USAGEHELP
Usage: $programname [random|edit]

Description:
  pick a game, or run a random one if "random" keyword argument specified


Created by Supersonic Tumbleweed AD 2018
USAGEHELP
}

if [[ $# > 1 ]]; then
  usage
  exit 1
fi

gamelist=/home/rne/useful/lists/games

function random_game() {
  shuf -n1 $gamelist
}

function choose_game() {
  choice=$(cat <(cat $gamelist) <(echo Anuluj) | fzf)
  if [[ "$choice" != "Anuluj" ]]; then
    echo $choice
  fi
}

if [[ $# == 1 ]]; then
  if [[ "$1" == "random" ]]; then
    game=$(random_game)
  elif [[ "$1" == "edit" ]]; then
    $EDITOR $gamelist
    exit 0
  else
    usage
    exit 1
  fi
fi

if [[ ! -v choice ]]; then
  game=$(choose_game)
  if [ -z "$game" ]; then
    echo Anulowano
    exit 0
  fi
fi

displayname=`expr "$game" : '.*#\(.*\)'`

echo Uruchamianie $displayname ...
sleep 3
eval $game
